<?php

namespace App\Services\Status;

/**
 * Class UserStatusService store all user statuses
 * @package App\Services
 */
class UserStatusService {

    const NEW = 'NEW';
    const DONE = 'DONE';

    const SELECT_MEDIA = 'SELECT_MEDIA';
    const SELECT_MEDIA_EDIT = 'SELECT_MEDIA_EDIT';
    const SELECT_PHOTO = 'SELECT_PHOTO';
    const SELECT_PHOTO_EDIT = 'SELECT_PHOTO_EDIT';
    const SELECT_VIDEO = 'SELECT_VIDEO';
    const SELECT_VIDEO_EDIT = 'SELECT_VIDEO_EDIT';
    const TITLE = 'TITLE';
    const TITLE_EDIT = 'TITLE_EDIT';
    const ABOUT = 'ABOUT';
    const ABOUT_EDIT = 'ABOUT_EDIT';
    const BUTTON_TEXT = 'BUTTON_TEXT';
    const BUTTON_TEXT_EDIT = 'BUTTON_TEXT_EDIT';
    const PREVIEW = 'PREVIEW';
    const EDIT = 'EDIT';

    const SELECT_SERVICE = 'SELECT_SERVICE';
    const SELECT_AUTO_SERVICE_SUBCATEGORY = 'SELECT_AUTO_SERVICE_SUBCATEGORY';
    const SELECT_AUTO_SERVICE_CLASS = 'SELECT_AUTO_SERVICE_CLASS';
    const SELECT_AUTO_SERVICE_RENT_PERIOD = 'SELECT_AUTO_SERVICE_RENT_PERIOD';
    const SELECT_AUTO_SERVICE_RENT_START = 'SELECT_AUTO_SERVICE_RENT_START';

    const SELECT_REAL_ESTATE_SUBCATEGORY = 'SELECT_REAL_ESTATE_SUBCATEGORY';
    const SELECT_REAL_ESTATE_CLASS = 'SELECT_REAL_ESTATE_CLASS';
    const SELECT_REAL_ESTATE_ROOM_COUNT = 'SELECT_REAL_ESTATE_ROOM_COUNT';
    const SELECT_REAL_ESTATE_RENT_PERIOD = 'SELECT_REAL_ESTATE_RENT_PERIOD';
    const SELECT_REAL_ESTATE_RENT_START = 'SELECT_REAL_ESTATE_RENT_START';

}